### ISSUE TITLE
Server failed to start (error in `LoggingOutputStream`)

### ISSUE THREAD

**Issue by Sitin** [Atigeo/spark-job-rest#12]
After `start_server.sh` I see no signs of life with only the following lines in logs:
```
2015-06-07 11:33:57 LoggingOutputStream$ [ERROR] Exception in thread "main" java.lang.NoSuchMethodError: akka.util.Helpers$.ConfigOps(Lcom/typesafe/config/Config;)Lcom/typesafe/config/Config;
	at akka.remote.RemoteSettings.<init>(RemoteSettings.scala:48)
	at akka.remote.RemoteActorRefProvider.<init>(Remo
2015-06-07 11:33:57 LoggingOutputStream$ [ERROR] teActorRefProvider.scala:114)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newIn
2015-06-07 11:33:57 LoggingOutputStream$ [ERROR] stance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	at scala.util.Try$.apply(Try.scala:161)
2015-06-07 11:33:57 LoggingOutputStream$ [ERROR] 
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(Dy
2015-06-07 11:33:57 LoggingOutputStream$ [ERROR] namicAccess.scala:84)
	at scala.util.Success.flatMap(Try.scala:200)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:550)
	at akka.actor.ActorSystem$.apply(ActorSystem.
```

**Comment by raduchilom** [comment]
There is a problem with the version of Typesafe Config.
This may be due to a difference of the spark dependecy that was used when building SJR and the actual spark you are using.
My skype id is raduchilom . We can chat if you'd like and I can give you some tips about how to solve this.
